name: compatible-test

on:
  push:
    branches: [ master, release-4.0 ]
  pull_request:
    branches: [ master, release-4.0 ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Free disk space
      run: |
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        docker volume prune -f
        docker image prune -f

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Pull images
      run: docker-compose -f docker-compose.yaml pull --ignore-pull-failures

    - name: Start server
      run: |
        docker-compose -f docker-compose.yaml rm -s -v
        docker-compose -f docker-compose.yaml build
        docker-compose -f docker-compose.yaml up --remove-orphans -d

    - name: Compatible test
      run: docker-compose -f docker-compose.yaml exec -T control make compatible_test
