name: compatible-test

on:
  push:
    branches: [ master, release-4.0 ]
  pull_request:
    branches: [ master, release-4.0 ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Generate Compatible test backup data
      run: sh compatible/prepare_backup.sh

    - name: Pull images
      run: TAG=nightly docker-compose -f compatible/backup_cluster.yaml pull --ignore-pull-failures

    - name: Start server
      run: |
        TAG=nightly PORT_SUFFIX=1 docker-compose -f docker-compose.yaml rm -s -v
        TAG=nightly PORT_SUFFIX=1 docker-compose -f docker-compose.yaml build
        TAG=nightly PORT_SUFFIX=1 docker-compose -f docker-compose.yaml up --remove-orphans -d
        timeout 8 sleep 5 || true
        TAG=nightly PORT_SUFFIX=1 docker-compose -f compatible/backup_cluster.yaml exec -T control make compatible_test

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: logs
        path: ${{ github.workspace }}/docker/logs/*
