name: compatible-test

on:
  push:
    branches: [ master, release-4.0 ]
  pull_request:
    branches: [ master, release-4.0 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Pull images
      run: docker-compose -f docker-compose.yaml pull --ignore-pull-failures

    - name: Build
      run: make compatible

    - name: Start server
      run: docker-compose up -d

    - name: Compatible test
      run: TEST_NAME=br_gcs make compatible
